language: android
android:
   components:
   - platform-tools
   - tools
   - build-tools-23.0.0-preview

jdk: oraclejdk8

notifications:
  email: true

sudo: false

script:
  - ./gradlew clean build
